### ISSUE TITLE
Attacks have a weird bonus 1

### ISSUE THREAD

**Issue by Katiemp013** [Xander-Carroll/xanders-swnr-sheet#4]
When attacking with a weapon that has an attack bonus, an extra "1" is being added to the ones place of the roll. In the attached image, I rolled three times: red is the base roll with no Xander sheet, purple is with an item attack bonus of 1, and blue is with an item attack bonus of 2.
![image](https://github.com/user-attachments/assets/0a07bfc9-4a4e-430f-8cf4-fac7bd3b02e2)

**Comment by Xander-Carroll** [comment]
This issue came from a type-o. Any time a skill with a positive bonus was used on an attack roll a "+" sign was missed. The issue was fixed in [v1.1.2](https://github.com/Xander-Carroll/xanders-swnr-sheet/releases/tag/v1.1.2).

Thank you for the amount of detail you gave in your report, it made it very easy to find and fix the issue.
